version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin        # root 계정 비밀번호
      MYSQL_USER: admin                 # 추가 사용자 계정
      MYSQL_PASSWORD: admin             # 추가 사용자 비밀번호
      MYSQL_DATABASE: bs-toy            # 초기 생성 데이터베이스
    volumes:
      - mariadb_data:/var/lib/mysql     # 데이터 지속화를 위한 볼륨
      - ./init-scripts:/docker-entrypoint-initdb.d  # 초기화 스크립트 마운트
    restart: unless-stopped

volumes:
  mariadb_data:
